/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class TagId extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class TagName extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class Tag extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    @Type(() => TagId)
    id?: TagId;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    @Type(() => TagName)
    name?: TagName;
}
