/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class LoginUserRequest extends SpeakeasyBase {
    /**
     * The password for login in clear text
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=password" })
    password?: string;

    /**
     * The user name for login
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=username" })
    username?: string;
}

export class LoginUserResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    headers: Record<string, string[]>;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * successful operation
     */
    @SpeakeasyMetadata()
    res?: string;

    /**
     * successful operation
     */
    @SpeakeasyMetadata()
    string?: string;
}
